// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportMonitorBlazor.Api.Models;

namespace SupportMonitorBlazor.Api.Migrations
{
    [DbContext(typeof(appDBContext))]
    [Migration("20210623063534_ForthMigration")]
    partial class ForthMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SupportMonitorBlazor.Models.BlazorTMS", b =>
                {
                    b.Property<int>("TmsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CriticalErrors")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TmsCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TmsId");

                    b.ToTable("BlazorTMS");

                    b.HasData(
                        new
                        {
                            TmsId = 1,
                            Country = "Norge",
                            KriticalErrors = 1,
                            Name = "Elkjøp",
                            TmsCategory = "TransFleet"
                        },
                        new
                        {
                            TmsId = 2,
                            Country = "Sverige",
                            KriticalErrors = 0,
                            Name = "Foria",
                            TmsCategory = "Tdxlog"
                        },
                        new
                        {
                            TmsId = 3,
                            Country = "Sverige",
                            KriticalErrors = 0,
                            Name = "LBC Logistik",
                            TmsCategory = "Tdxlog"
                        },
                        new
                        {
                            TmsId = 4,
                            Country = "Finland",
                            KriticalErrors = 0,
                            Name = "Gigantti OY",
                            TmsCategory = "TransFleet"
                        },
                        new
                        {
                            TmsId = 5,
                            Country = "Felles nordisk",
                            KriticalErrors = 0,
                            Name = "DSV",
                            TmsCategory = "TransFleet"
                        },
                        new
                        {
                            TmsId = 6,
                            Country = "Norsk",
                            KriticalErrors = 0,
                            Name = "Gausdal Skurlag",
                            TmsCategory = "TransFleet"
                        },
                        new
                        {
                            TmsId = 7,
                            Country = "Norsk",
                            KriticalErrors = 0,
                            Name = "Brødrene Dahl",
                            TmsCategory = "TransFleet"
                        },
                        new
                        {
                            TmsId = 8,
                            Country = "Norsk",
                            KriticalErrors = 0,
                            Name = "Alvdal Skurlag",
                            TmsCategory = "TransFleet"
                        },
                        new
                        {
                            TmsId = 9,
                            Country = "Norsk",
                            KriticalErrors = 1,
                            Name = "Østfold Olje Ragnar Larsen & Sønner",
                            TmsCategory = "TransFleet"
                        },
                        new
                        {
                            TmsId = 10,
                            Country = "Norsk",
                            KriticalErrors = 0,
                            Name = "Toll",
                            TmsCategory = "TransFleet"
                        },
                        new
                        {
                            TmsId = 11,
                            Country = "Sverige",
                            KriticalErrors = 0,
                            Name = "Wiklunds",
                            TmsCategory = "Tdxlog"
                        },
                        new
                        {
                            TmsId = 12,
                            Country = "Sverige",
                            KriticalErrors = 0,
                            Name = "LBC Logistik",
                            TmsCategory = "Tdxlog"
                        },
                        new
                        {
                            TmsId = 13,
                            Country = "Sverige",
                            KriticalErrors = 0,
                            Name = "LBC Tingsryd",
                            TmsCategory = "Tdxlog"
                        },
                        new
                        {
                            TmsId = 14,
                            Country = "Sverige",
                            KriticalErrors = 1,
                            Name = "Örnfrakt",
                            TmsCategory = "Tdxlog"
                        },
                        new
                        {
                            TmsId = 15,
                            Country = "Sverige",
                            KriticalErrors = 0,
                            Name = "Fraktkedjan Anläggning AB",
                            TmsCategory = "Tdxlog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
