// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportMonitorBlazor.Api.Models;

namespace SupportMonitorBlazor.Api.Migrations
{
    [DbContext(typeof(appDBContext))]
    [Migration("20210623062118_TestMigration")]
    partial class TestMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SupportMonitorBlazor.Models.BlazorTMS", b =>
                {
                    b.Property<int>("TmsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CriticalErrors")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TmsCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TmsId");

                    b.ToTable("BlazorTMS");

                    b.HasData(
                        new
                        {
                            TmsId = 1,
                            Country = "Norge",
                            KriticalErrors = 1,
                            Name = "Elkjøp",
                            TmsCategory = "TransFleet"
                        },
                        new
                        {
                            TmsId = 2,
                            Country = "Sverige",
                            KriticalErrors = 0,
                            Name = "Foria",
                            TmsCategory = "Tdxlog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
